# Generated by Django 2.0.6 on 2018-07-13 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_giftcloud', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(default='', max_length=256)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Platform',
        ),
        migrations.RenameField(
            model_name='gift',
            old_name='gift_status_choices',
            new_name='gift_choices',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='birthday',
            new_name='birthdate',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='full_name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='gitfs',
            field=models.ManyToManyField(to='app_giftcloud.Gift'),
        ),
        migrations.AddField(
            model_name='gift',
            name='price',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='gift',
            name='share_choices',
            field=models.CharField(choices=[('FB', 'Facebook'), ('TW', 'Twitter'), ('EM', 'Email')], default='FB', max_length=2),
        ),
        migrations.AddField(
            model_name='gift',
            name='store_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='gifts',
            field=models.ManyToManyField(to='app_giftcloud.Gift'),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='password',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='gift',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(default='', max_length=13),
        ),
    ]
