# Generated by Django 2.0.6 on 2018-07-16 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_giftcloud', '0004_auto_20180716_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
    ]
