# Generated by Django 2.0.6 on 2018-07-19 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_giftcloud', '0005_auto_20180716_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='priority_choices',
            field=models.CharField(choices=[('FB', 'Facebook'), ('TW', 'Twitter'), ('EM', 'Email')], default='LW', max_length=2),
        ),
    ]
