# Generated by Django 2.0.7 on 2018-07-19 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_giftcloud', '0006_gift_priority_choices'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gift',
            old_name='text',
            new_name='gift_description',
        ),
        migrations.RemoveField(
            model_name='gift',
            name='priority_choices',
        ),
        migrations.AlterField(
            model_name='gift',
            name='gift_choices',
            field=models.CharField(choices=[('PB', 'Public'), ('PI', 'Private')], default='PB', max_length=2),
        ),
    ]
