# Generated by Django 2.0.6 on 2018-07-19 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_giftcloud', '0007_auto_20180719_2213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gift',
            old_name='gift_description',
            new_name='gift_details',
        ),
        migrations.AddField(
            model_name='gift',
            name='gift_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='gift',
            name='link_url',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='gift',
            name='quantity',
            field=models.CharField(default='', max_length=50),
        ),
    ]
