# Generated by Django 2.0.6 on 2018-07-20 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_giftcloud', '0008_auto_20180719_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='gift_details',
            field=models.TextField(null=True),
        ),
    ]
