# Generated by Django 2.0.6 on 2018-07-23 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_giftcloud', '0014_auto_20180722_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='gifts',
        ),
        migrations.AddField(
            model_name='gift',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_giftcloud.Profile'),
        ),
    ]
