# Generated by Django 2.0.6 on 2018-07-24 01:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_giftcloud', '0016_gift_user_base'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gift',
            name='user_base',
        ),
        migrations.AddField(
            model_name='profile',
            name='user_base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
