# Generated by Django 2.0.6 on 2018-07-26 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_giftcloud', '0018_auto_20180725_2311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='email',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='full_name',
        ),
        migrations.AddField(
            model_name='contact',
            name='date_joined',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='contact',
            name='following',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='following_fk', to='app_giftcloud.Profile'),
        ),
        migrations.AddField(
            model_name='contact',
            name='invite_reason',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='contact',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followers_fk', to='app_giftcloud.Profile'),
        ),
    ]
