# Generated by Django 2.0.6 on 2018-07-27 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_giftcloud', '0019_auto_20180726_0204'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='img_gift',
            field=models.ImageField(default=None, upload_to=None),
        ),
    ]
