# Generated by Django 2.0.6 on 2018-07-27 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_giftcloud', '0020_gift_img_gift'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gift',
            old_name='img_gift',
            new_name='img_url',
        ),
    ]
