# Generated by Django 2.0.6 on 2018-07-27 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_giftcloud', '0021_auto_20180727_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='img_url',
            field=models.CharField(default='', max_length=500),
        ),
    ]
